spring:
  profiles:
    active: demo

server:
  servlet:
    context-path:

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5433/javademo
    username: postgres
    password:
    pool-size: 30


