spring:
  profiles:
    group:
      dev: local,dev

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://database-studentcoursemanagement1.cw3xcmetl0yh.eu-west-1.rds.amazonaws.com:5433/studentcourse
    username: lorraineyul
    password: jiaxuan13882060
    pool-size: 30


